### ISSUE TITLE
[Traefik Plugin Catalog] Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [scrazy77/customerrorsrewrite#1]
The plugin was not imported into Traefik Plugin Catalog.

Cause:
```
the import "github.com/scrazy77/customerrorsrewrite" must be related to the module name "customerrorsrewrite"
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.traefik.io/).

**Comment by scrazy77** [comment]
https://github.com/scrazy77/customerrorsrewrite/releases/tag/v0.0.2
